version: "3"

services:
  web:
    image: vedisback/nginx:1.15v6
    container_name: "d8_nginx"
    ports:
      - $NGINX_PORT:$NGINX_PORT
    volumes:
      - "./drupal/web:/var/www/html"
      - "./drupal/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php

  php:
    image: drupal:$DRUPAL_TAG
    container_name: "$d8_php-fpm"
    volumes:
      - "./drupal/web:/var/www/html"
    restart: always
    depends_on:
      - mysql
  mysql:
      image: mysql:$MYSQL_TAG
      container_name: "d8_mysql"
      entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
      environment:
        MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        MYSQL_USER: $DB_USER
        MYSQL_PASSWORD: $DB_PASSWORD
        MYSQL_DATABASE: $DB_NAME
      volumes:
        - "./drupal/mysql:/var/lib/mysql"
      restart: always
